runtime: custom # or custom for app deploy, not run deploy which is python39
env: flex
entrypoint: gunicorn -w 4 -b :$PORT app:app  # Number of workers set to 4

#manual_scaling:
#  instances: 1  # You can adjust the number of instances

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4  # Allows scaling up to 4 instances based on demand
  cool_down_period_sec: 60

resources:
  cpu: 4  # Increased from 2 to 4
  memory_gb: 8  # Increased from 4 to 8
  disk_size_gb: 20  # Adjust the disk size as needed

runtime_config:  # Specify the python version
  operating_system: ubuntu22

env_variables:
  # Environment variables can be placed here, if needed.