runtime: custom # or custom for app deploy, not run deploy which is python39
env: flex
entrypoint: gunicorn -b :$PORT app:app

manual_scaling:
  instances: 1  # You can adjust the number of instances

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20  # Adjust the disk size as needed

runtime_config:  # Specify the python version
  operating_system: ubuntu22

env_variables:
  # Environment variables can be placed here, if needed.